---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle
    tag: latest

inputs:
- name: trades-repo
- name: version

outputs:
- name: zip-files

run:
  path: trades-repo/ci/tasks/build-trades-package.sh

caches:
- path: .m2/

