---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle
    tag: latest

inputs:
- name: gcp-spanner-example

outputs:
- name: zip-files

run:
  path: gcp-spanner-example/ci/tasks/build-gcp-spanner-example-package.sh

caches:
- path: .m2/

