---

resources:

- name: trades-repo
  type: git
  source:
    uri: https://github.com/primetimesoftware/trades.git
    branch: master
    depth: 1

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/primetimesoftware/trades.git
    branch: master
    file: version
    depth: 1
    username: ((github_username))
    password: ((github_password))

- name: trades-release
  type: github-release
  source:
    owner: primetimesoftware
    repository: trades
    access_token: ((github_password))

jobs:

- name: build-trades-package
  serial_groups: [keep-it-simple]
  plan:
  - get: version
    params: {bump: minor}
  - get: trades-repo
  - task: build-trades-package
    file: trades/ci/tasks/build-trades-package.yml
  - put: version
    params: {file: version/version}
  - put: trades-release
    params:
      name: zip-files/release-name
      tag: zip-files/release-tag
      globs:
      - zip-files/trades.zip